users:
  documentID: userID
  email: string
  uid: userID
  expense:
    documentID: auto
    cretaedAt: Date
    date: Date
    amount: number
    tag: string
  tags:
    tag1: boolean
    tag2: boolean
    # and more
