users:
  documentId: userId,
  income:
    documentId: auto
    createdAt: Date
    date: Date
    amount: number

  expense:
    documentId: auto
    cretaedAt: Date
    date: Date
    amount: number
